// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Visiolock();
Q_GHS_KEEP_REFERENCE(qml_register_types_Visiolock)

class VisiolockPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    VisiolockPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Visiolock;
        Q_UNUSED(registration)
    }
};



#include "Visiolockplugin_VisiolockPlugin.moc"
