
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/matthieu/logiciels/Qt/Tools/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-14-generic - x86_64
...
